### ISSUE TITLE
Unable to find a suitable main class, please add a 'mainClass' property

### ISSUE THREAD

**Issue by logtous** [zhy6599/cc-admin-api#5]
java小白，特来请教。`wsl2 ubuntu20`环境运行,目前`mvn install`完成，手工安装了sqlserver和oracel的mvn包，最后运行`mvn spring:boot run`提示如下：
![NHILIZU$FE`_W7~} L 8V6Y](https://user-images.githubusercontent.com/88697234/141448334-ed7b443a-e5f6-4260-9294-2f4b065ccf22.png)

**Comment by zhy6599** [comment]
- 首先下载代码到本地，然后使用ide对代码进行编译运行，确保本地运行没问题。

- 用mvn进行打包，cc-admin-api下的Lifecycle下的package，脚本会自动将所有程序和依赖打包成zip包，打包好的文件路径是 cc-admin-api\module-system\target ，将module-system-1.0-xxxx.zip 上传到服务器，解压缩。

- linux下进入bin目录先执行chmod 777 * 添加可执行权限，然后执行./catalina.sh start启动项目，停止是 ./catalina.sh stop 查看状态是./catalina.sh status，可以执行./log.sh 查看运行日志。   

- window下直接运行 startup.bat即可。
